name: Deploy Backend
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy-frontend-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull from GitHub repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/HTN-Backend-Challenge-2023
            git reset --hard
            git pull
            yarn
            pm2 reload 8